### ISSUE TITLE
Run id not returned on console

### ISSUE THREAD

**Issue by madhu-jain** [GoogleCloudPlatform/professional-services-data-validator#713] opened 2023-02-09 12:11 UTC
The DVT execution does not provide a response code with the run_id on command line execution, the user needs to go into bigquery and search the execution results to find the appropriate run_id. This becomes more cumbersome when multiple executions of DVT is done at same time.

**Comment by Raniksingh** [comment] 2023-02-09 14:22
Duplicate of issue #686 .
Fix provided by PR #708

**Closed as completed** 2023-02-09 14:22 UTC
