### ISSUE TITLE
Adding support for complex Data Types for tables in Hive 

### ISSUE THREAD

**Issue by rohangoogle** [GoogleCloudPlatform/professional-services-data-validator#697] opened 2023-02-02 05:06 UTC
Currently we cannot perform row level checks on tables that has complex data types such as Struct, Array or Record type. Adding this feature will help to test the data at row level.

**Comment by Raniksingh** [comment] 2023-02-09 14:32
Duplicate of Issue #88. Hence closing this.

**Closed as completed by Raniksingh** 2023-02-09 14:32 UTC
