### ISSUE TITLE
FR: Enable random number of full row tests between source and destination

### ISSUE THREAD

**Issue by dhaval-d** [GoogleCloudPlatform/professional-services-data-validator#142] opened 2020-11-18 23:33 UTC
One of the customers requested to have an ability to randomly select and compare entire set of rows between source and destination systems. 

Can we implement this functionality?

**Comment by nehanene15** [comment] 2022-04-01 15:21
Duplicate of #374

**Closed by nehanene15** 2022-04-01 15:21 UTC
Labels: type: feature request, priority: p0, Release
