### ISSUE TITLE
Row Validation : Field Comparison between DB2 and Big query for random 40k records throws error

### ISSUE THREAD

**Issue by madhu-jain** [GoogleCloudPlatform/professional-services-data-validator#742] opened 2023-02-18 18:59 UTC
**Description :**
For a source (DB2) and target table (Bigquery) having record count of ~8 mn, when row validation performed for random 40000 rows with 9 columns, it was throwing error whereas when done for 30000 record, it ran successfully. Below command ran :

data-validation validate row \
-sc DB2_CONN \
-tc BQ_CONN \
-tbls DB2INST1.STOCK_PRICE_DVT=rite-aid-371612.bq_dvt.stock_price_dvt \
--primary-keys id \
-comp-fields stk_id,symbol,stock_date,high,low,volume,adjusted,stock_load_date,is_active \
-rr \
-rbs 40000 \
--bq-result-handler rite-aid-371612.data_validator.results

**Error :** 

Exception: Statement Execute Failed: [IBM][CLI Driver] CLI0100E  Wrong number of parameters. SQLSTATE=07001 SQLCODE=-99999

Is there any limit on random records for DB2?

**Comment by nehanene15** [comment] 2023-03-28 19:53
Duplicate of #718

**Closed as completed by nehanene15** 2023-03-28 19:53 UTC
Labels: type: bug
