### ISSUE TITLE
Hash Comparison not supported for DB2 to Bigquery Row Validation

### ISSUE THREAD

**Issue by madhu-jain** [GoogleCloudPlatform/professional-services-data-validator#703] opened 2023-02-06 09:50 UTC
Trying to do Row Validation using Hash Comparison between DB2 (source) and Bigquery (target) using below command : 

data-validation validate row \
--source-conn DB2_CONN \
--target-conn BQ_CONN \
--tables-list POCDB2.customer=rite-aid-371612.bq_dvt.customer_db2_df \
--hash '*' \
--primary-keys custid \
--use-random-row \
--random-row-batch-size 2 \
--bq-result-handler rite-aid-371612.data_validator.results

Error : 

raise com.OperationNotDefinedError(
ibis.common.exceptions.OperationNotDefinedError: No translation rule for <class 'third_party.ibis.ibis_addon.operations.HashBytes'>

Also Randow row sampling is not supported in DB2 

**Error :** 

Data Client <class 'third_party.ibis.ibis_DB2.client.DB2Client'> Does Not Enforce Random Sort on Sample

**Comment by Raniksingh** [comment] 2023-02-09 14:18
Duplicate of issue #692 
Adding Row validation feature will by default adds hash functionality.

**Closed as completed** 2023-02-09 14:20 UTC
