### ISSUE TITLE
Row level validation with Hive broken due to column casing

### ISSUE THREAD

**Issue by RajeevGCP** [GoogleCloudPlatform/professional-services-data-validator#528] opened 2022-06-28 20:58 UTC
BQ to Hive row level comparison for hash or  random batch doesn't work when hive has columns in Upper case. 

Typical error thrown is "COLUMN_NAME" not found "column_name" list.

Different alias combination and calculated fields were also tested but no luck.

**Comment by piyushsarraf** [comment] 2022-10-10 07:07
Hi Rajeev, 
Can u please help me with steps to reproduce the error ? 

Because by default hive column do not have upper casing in column names.

**Comment by nehanene15** [comment] 2022-11-22 19:29
This should be resolved with PR #626

**Closed as completed by nehanene15** 2022-11-22 19:29 UTC
