### ISSUE TITLE
Group by Validation - Inconsistent Null values for datetime columns

### ISSUE THREAD

**Issue by srikanthgaddam2** [GoogleCloudPlatform/professional-services-data-validator#447] opened 2022-04-18 19:16 UTC
![image](https://user-images.githubusercontent.com/103214226/163863727-12719268-d137-42e4-b8a8-1f3b69c14387.png)

Null datetimestamp column when included in Group By validation..the null value is interpreted inconsistently (NaT/None) for comparison.

**Comment by nehanene15** [comment] 2022-04-18 19:49
Is it inconsistent for the same data source? I.e sometimes NaT in BigQuery will show up as 'NaT' and other times they will be 'None'?

**Comment by srikanthgaddam2** [comment] 2022-04-18 20:25
@nehanene15 yes it is consistent 'NaT' for big query and 'None' for teradata

**Comment by nehanene15** [comment] 2022-04-29 03:47
Ideally for this one we can find a way for BigQuery to return 'None' for NULL timestamp values if possible. Otherwise, we would have to manually replace the 'NaT' values in the source/target data frames.

**Comment by ngdav** [comment] 2022-04-29 18:39
I'm wondering if we return None instead of NaT, it'll be hard to differentiate between a result that is NULL vs just no data was returned.

**Comment by nehanene15** [comment] 2022-05-02 01:53
Wouldn't those two be the same thing? We only get NaT when there is a timestamp column value that is NULL.

**Comment by nehanene15** [comment] 2023-07-18 19:55
Duplicate of #426

**Closed as completed by nehanene15** 2023-07-18 19:55 UTC
Labels: type: bug, priority: p2
