### ISSUE TITLE
MSSQL vs BQ - Row Validation - Custom Query comparison using yaml throwing error

### ISSUE THREAD

**Issue by madhu-jain** [GoogleCloudPlatform/professional-services-data-validator#716] opened 2023-02-10 11:24 UTC
Comp field comparison between SQL server and Big query for few columns (INT and STRING datatype) using YAML config throwing error.

**Command used :** 

data-validation validate row \
-sc MSSQL_CONN \
-tc BQ_CONN \
-tbls tempdb.dbo.customer=paras-sandbox-364713.dlp.customer \
--primary-keys custid \
-comp-fields custname,age \
--bq-result-handler paras-sandbox-364713.data_validator.results \
--config-file customer_rv.yaml

**YAML :** (Generated YAML modified to remove source/target details and add custom query)

result_handler:
  project_id: paras-sandbox-364713
  table_id: data_validator.results
  type: BigQuery
source: MSSQL_CONN
target: BQ_CONN
validations:
- calculated_fields: []
  comparison_fields:
  - cast: null
    field_alias: custname
    source_column: custname
    target_column: custname
  - cast: null
    field_alias: age
    source_column: age
    target_column: age
  filter_status: null
  filters: []
  format: table
  labels: []
  primary_keys:
  - cast: null
    field_alias: custid
    source_column: custid
    target_column: custid
  random_row_batch_size: null
  source_query: select custid,custname,age from dbo.customer 
  table_name: null
  target_query: select custid,custname,age from paras-sandbox-364713.dlp.customer
  target_schema_name: null
  target_table_name: null
  threshold: 0.0
  type: Custom-query 
  use_random_rows: false

**Error :** 

AttributeError: 'str' object has no attribute 'alias'

**Comment by Raniksingh** [comment] 2023-02-17 10:38
Comp field support now added to custom query with PR #701

**Comment by Raniksingh** [comment] 2023-02-17 11:29
Duplicate of Issue #694

**Closed as completed** 2023-02-21 04:12 UTC
Labels: priority: p1
