### ISSUE TITLE
Row Validation : Field Comparison between SQL server and Big query for random 2200 records throws error

### ISSUE THREAD

**Issue by madhu-jain** [GoogleCloudPlatform/professional-services-data-validator#741] opened 2023-02-18 18:43 UTC
**Description :** 
For a source (SQL Server) and target table (Bigquery) having record count of ~13 mn, when row validation performed for random 2200 rows with 7 columns, it was throwing error whereas when done for 2000 record, it ran successfully. Below command ran : 

data-validation validate row \
-sc MSSQL_CONN \
-tc BQ_CONN \
-tbls tempdb.dbo.dvt_prices=paras-sandbox-364713.dlp.dvt_prices \
--primary-keys sr_no \
-comp-fields symbol,log_date,close_stock,volume,adjusted,stock_load_date,is_active \
-rr \
-rbs 2200 \
--bq-result-handler paras-sandbox-364713.data_validator.results

Is there any limit on random records for SQL Server?

**Comment by nehanene15** [comment] 2023-03-28 19:26
Duplicate of #711

**Closed as completed by nehanene15** 2023-03-28 19:26 UTC
Labels: type: bug
