### ISSUE TITLE
Teradata to BQ - TypeError: "Cannot change data-type for object array"

### ISSUE THREAD

**Issue by helensilva14** [GoogleCloudPlatform/professional-services-data-validator#1097] opened 2024-02-20 18:30 UTC
- Happening with custom-query validation in a table with composite PK (integer, datetime).
- No array in any table (source or target)
- Using comparison fields
- Custom-query only being used as a workaround to case sensitivity issue

![image](https://github.com/GoogleCloudPlatform/professional-services-data-validator/assets/37883833/0efb9147-742a-4aef-833d-f82bfa7cae61)

**Comment by helensilva14** [comment] 2024-02-23 18:29
Hi @paolocanaletti and @elena-gottardi-nttdata, happy Friday! 

Since this approach was used as a workaround for the case sensitivity issue and it was resolved in the new release (https://github.com/GoogleCloudPlatform/professional-services-data-validator/releases/tag/v4.4.0), could you please retry this scenario to see if you still get this error? Thanks!

**Comment by nehanene15** [comment] 2024-03-15 18:42
Issue is due to large timestamps - duplicate of Issue #1053

**Closed as not planned by nehanene15** 2024-03-15 18:42 UTC
Labels: type: bug, priority: p0
