### ISSUE TITLE
Row Validation - Random rows not supported in BQ to BQ row comparison

### ISSUE THREAD

**Issue by madhu-jain** [GoogleCloudPlatform/professional-services-data-validator#785] opened 2023-03-28 20:48 UTC
Description :  While running row validation between Bigquery External table and Bigquery Native table with random rows, it ran for entire data despite providing row batch size. Command used : 

data-validation validate row \
-sc BQ_CONN \
-tc BQ_CONN \
--tables-list rite-aid-pocs.ra_landing_ext.perpetual_inventory_ext=rite-aid-pocs.ra_landing.perpetual_inventory \
-comp-fields store,store_onhand_units,perpetual_inventory_dte,replenishment_ind \
-pk original_item_nbr \
-rr \
-rbs 1 \
--bq-result-handler rite-aid-pocs.ra_data_validation.results

**Comment by nehanene15** [comment] 2023-07-18 19:31
This could be an issue if original_item_nbr is not a unique PK. I would also try increasing the batch size. 
Please re-open if this is still an issue; I'm closing it since I've seen newer issues opened where this works as intended.

**Closed as completed by nehanene15** 2023-07-18 19:31 UTC
Labels: priority: p1
