### ISSUE TITLE
Cast datatype for comparison field for row validation incorrect in config yielding weird error like EOF.

### ISSUE THREAD

**Issue by rishabkhawad** [GoogleCloudPlatform/professional-services-data-validator#968] opened 2023-09-01 07:46 UTC
The config generated for custom query row validations has incorrect datatype (datetime) which yield weird errors like below:

This seems to be an extension of this issue - https://github.com/GoogleCloudPlatform/professional-services-data-validator/pull/957 . 

DVT command - 

```
data-validation validate custom-query -sc td_conn -tc bq_conn -sqf td.sql -tqf bq.sql --primary-keys col_a 
-comp-fields {cols}  -bqrh project.result_table -c config.yaml 
```

Config generated - 
```
result_handler:
  project_id: <project>
  table_id: <projectid.simba>.<table_id>
  type: BigQuery
source: td_conn
target: bq_conn
validations:
- calculated_fields: []
  comparison_fields:
  - cast: float64
    field_alias: col
    source_column: col
    target_column: col
  - cast: float64
    field_alias: col-b
    source_column: col-b
    target_column: col-b
  - cast: string
    field_alias: col
    source_column: col
    target_column: col
  - cast: DATETIME
    field_alias: col
    source_column: col
    target_column: col
  - cast: DATE
    field_alias: col
    source_column: col
    target_column: col
  - cast: string
    field_alias: col
    source_column: col
    target_column: col
  - cast: DATETIME
    field_alias: col
    source_column: col
    target_column: col
  - cast: DATE
    field_alias: col
    source_column: col
    target_column: col
  - cast: string
    field_alias: col
    source_column: col
    target_column: col
  - cast: string
    field_alias: col
    source_column: col
    target_column: col
  - cast: float64
    field_alias: case_scr
    source_column: col
    target_column: col
  - cast: DATETIME
    field_alias: col
    source_column: col
    target_column: col
  - cast: DATETIME
    field_alias: col
    source_column: col
    target_column: col
  custom_query_type: row
  filter_status: null
  filters: []
  format: table
  labels: []
  primary_keys:
  - cast: float64
    field_alias: col-a
    source_column: col-a
    target_column: col-a
  random_row_batch_size: null
  schema_name: null
  source_query: sselect {cols} where case_hist_id in (24765102081)
  table_name: null
  target_query: select {cols} where case_hist_id in (24765102081)
  target_schema_name: null
  target_table_name: null
  threshold: 0.0
  type: Custom-query
  use_random_rows: false
```

Error output while running the config file -   
![image](https://github.com/GoogleCloudPlatform/professional-services-data-validator/assets/118872983/98479c33-0479-4305-9fe2-0f03972dead4)

**Comment by nehanene15** [comment] 2023-09-05 21:28
Can't reproduce this because DVT doesn't populate the comparison field cast for row validations.

Here is the command: `data-validation validate custom-query row -sc bq -tc bq -sqf query.sql -tqf query.sql -pk id -comp-fields id,name,age -c config.yaml`

Here is the YAML generated:
```yaml
result_handler: {}
source: bq
target: bq
validations:
- calculated_fields: []
  comparison_fields:
  - cast: null
    field_alias: id
    source_column: id
    target_column: id
  - cast: null
    field_alias: name
    source_column: name
    target_column: name
  - cast: null
    field_alias: age
    source_column: age
    target_column: age
  custom_query_type: row
  filter_status: null
  filters: []
  format: table
  labels: []
  primary_keys:
  - cast: null
    field_alias: id
    source_column: id
    target_column: id
  random_row_batch_size: null
  schema_name: null
  source_query: 'select id, name, age from hivetest.nulltest_diff '
  table_name: null
  target_query: 'select id, name, age from hivetest.nulltest_diff '
  target_schema_name: null
  target_table_name: null
  threshold: 0.0
  type: Custom-query
  use_random_rows: false
```

Was this generated by automation wrapping DVT or the tool itself?

**Comment by nehanene15** [comment] 2023-09-20 17:54
@rishabkhawad Following up on this - are we still seeing this error?

**Comment by rishabkhawad** [comment] 2023-09-26 05:11
@nehanene15 i am not sure how the cast fields got populated, but we did not add them manually.

**Comment by nehanene15** [comment] 2023-10-16 13:56
@rishabkhawad  Can you provide the schema of the table?

**Comment by nehanene15** [comment] 2024-01-22 18:32
Wasn't able to reproduce so closing for now

**Closed as not planned by nehanene15** 2024-01-22 18:32 UTC
Labels: type: bug
