### ISSUE TITLE
Schema validation for column names are case sensitive  Build 2.0

### ISSUE THREAD

**Issue by bnb012008** [GoogleCloudPlatform/professional-services-data-validator#495] opened 2022-06-01 20:49 UTC
I am comparing schema's between a BQ table and a DB2 table.  The BQ table was created using an AVRO file that was created from the DB2 source table.  I know there has been a case sensitive issue in DVT column validation but you can correct for that using a the yaml file.  Is there any way to allow case insensitive compares for column names with Schema validation?  Is there a yaml file correction that can be used for schema compares?

**Comment by nehanene15** [comment] 2022-06-01 21:16
Closing because this is a duplicate of Issue #385 which is being prioritized.
Currently schema compares only support a case sensitive match via CLI or YAML.

**Closed as completed by nehanene15** 2022-06-01 21:16 UTC

**Comment by bnb012008** [comment] 2022-06-01 22:28
Thank you!
