### ISSUE TITLE
Bug: String primary keys between Teradata and BigQuery are not matching

### ISSUE THREAD

**Issue by franklinWhaite** [GoogleCloudPlatform/professional-services-data-validator#1151] opened 2024-05-29 22:25 UTC
When a character primary key is used in a Teradata vs BigQuery row validation, the keys do not match. The output table shows trailing whitespaces in the keys from Teradata even though those whitespaces are not present in the Teradata table.

The same error persists when using composite primary keys that contain at least one CHAR typed column.

**Comment by nj1973** [comment] 2024-05-31 16:05
I've added some tests to an attached branch.

I added tests for VARCHAR and CHAR primary keys for Teradata vs BigQuery and Oracle vs BigQuery.

The VARCHAR test passes on Teradata but the CHAR one fails. Both pass on Oracle.

The problem I am seeing is that the trailing spaces are being doubled up. My column is CHAR(6) but the values returned from teradata are length 12.

```
(Pdb) p [len(_) for _ in source_df['id']]
[12, 12, 12, 12, 12]
(Pdb) p [len(_) for _ in target_df['id']]
[6, 6, 6, 6, 6]
```

@franklinWhaite , can you clarify exactly what data type and length has been used in Teradata please? You mentioned string in the issue title but char in the body, it would be nice to know exactly what type you've used.

**Comment by nehanene15** [comment] 2024-05-31 20:13
@nj1973 Thanks for researching! I know they were testing with CHAR(10) data type in TD. They mentioned even when they have a composite PK with a CHAR column, they are seeing the mismatching keys.

I think we may need to add a trim() for CHAR PKs in Teradata...

**Comment by nj1973** [comment] 2024-06-03 12:33
> I think we may need to add a trim() for CHAR PKs in Teradata...

We would need to do it across all engines. AFAIK most engines support a padded CHAR data type where values are padded to a specific length. I've never seen one used as a primary key before though. It seems we should first try to understand why the padded length on Teradata is different to the defined on the column.

**Comment by sundar-mudupalli-work** [comment] 2024-06-04 03:47
Hi,

Most traditional databases support a fixed length character field and pad the field with spaces. This is typical COBOL/FORTRAN. I think C was the first language that supported variable length strings (which require garbage collection).

I am not sure we should be trimming primary keys. A primary key has to have a unique value. We would be comparing a fixed length string (Teradata) with a variable length string (BQ) and declare them equal even though they are of different lengths. At DVT, I think our role is to validate the data, not interpret it. The customer trimmed it before saving it to BQ. They can do the trim pretty easily using the ibis function rstrip in the yaml file during the validation

Regarding the specific issues reported by the customer

1. fixed length character strings are returned as fixed length character strings padded with spaces. 
2. the teradataSQL package which uses variable length character set documented [here](https://github.com/Teradata/python-driver?tab=readme-ov-file#character-export-width) - which causes additional padding as observed by Neil.

This is expected behavior with a simple workaround - not a bug in my opinion

Sundar Mudupalli

**Comment by nj1973** [comment] 2024-06-04 11:01
I agree we should not be trimming primary keys across the board. It did cross my mind if we could safely trim Teradata CHARs to the expected length. For example if the column is CHAR(6) and contains `"ABCD  "` the client will return `"ABCD        "` (length of 12). We could substr it back to expected length of 6. However, in DVT we don't whether a string column is VARCHAR or CHAR, so we could be adding string manipulation to many validations that don't need it.

The added complication that the BigQuery data has been trimmed anyway means any fix/workaround to get accurate CHAR behaviour will be rendered obsolete anyway.

I added a few more tests to the branch:

- PostgreSQL behaves as expected
- MySQL is a problem due to requirement for `PAD_CHAR_TO_FULL_LENGTH` which we should investigate
- Snowflake does not have padded CHAR semantics therefore is out of scope

**Comment by nehanene15** [comment] 2024-06-05 15:44
Maybe the PK trim is something we can add specifically for Teradata string primary keys - regardless of whether it's a char/varchar. We initially added the rstrip to hash/concat validation to account for this TD padding issue.

The only concern with going this route would be if a user is comparing TD to another DB with padded CHAR semantics and then fails because of the rstrip. But this is uncommon since most of our TD users compare with BQ.

@nj1973 @sundar-mudupalli-work Any thoughts on adding the rstrip to TD string PKs?

**Comment by sundar-mudupalli-work** [comment] 2024-06-06 07:17
Hi,

DVT should not interpret data - just validate it - however we have to work with what is common "parlance" in the data migration world - that is, strings padded with blanks are "equal" to strings that don't have the trailing blanks - as long as we comparing them with hashes. We already do this today.

So Neha is correct - we don't do it for primary keys. Trimming primary keys sounds bad - this customer needs it and [a bug in Teradata python driver for fixed length character fields](https://github.com/Teradata/python-driver?tab=readme-ov-file#character-export-width) exacerbates the problem. The good news is that if we ask ibis to trim the primary key in the query (just for Teradata) - the fixed length string becomes a variable length string and the Teradata driver bug does not affect the result. Perhaps we do this just for Teradata for now and see if other customers have this need.

This is a change in [data_validation/query_builder/query_builder.py](https://github.com/GoogleCloudPlatform/professional-services-data-validator/compare/develop...1151-string-primary-keys-teradata#diff-2f13d91dc64cdd3c18ce9e4a40b10b5b8661a7dd3849b6838c1f4b92569beb2f) - which I have checked into the [1151-string-primary-keys-teradata](https://github.com/GoogleCloudPlatform/professional-services-data-validator/tree/1151-string-primary-keys-teradata) branch. I tested it on Franklin's examples and they were all successful. There is probably an opportunity to check it does not affect things other than row validation.

Please review and let us discuss.

Cheers.

Sundar Mudupalli

**Closed as completed** 2024-06-11 13:21 UTC
Labels: type: bug, priority: p0
