### ISSUE TITLE
Data Validator - Custom Query - Inline Query Support 

### ISSUE THREAD

**Issue by Murli16** [GoogleCloudPlatform/professional-services-data-validator#695] opened 2023-02-02 04:00 UTC
The data validator custom query feature does not currently support providing inline queries.

Is there a plan to add the feature as it would simplify the execution and remove dependency for smaller queries from having sql files.

**Comment by nehanene15** [comment] 2023-02-06 15:33
Closing as duplicate of #674

**Closed as completed by nehanene15** 2023-02-06 15:33 UTC
