### ISSUE TITLE
Row validation fails if primary key column name is of different case in source and target

### ISSUE THREAD

**Issue by giovanni-girelli-sdg** [GoogleCloudPlatform/professional-services-data-validator#467] opened 2022-05-04 09:43 UTC
As in the title, it fails to use the alias information that is present in the config. The column is present in the source as clientele_region_id. The config file correctly shows:

```
- cast: null
    field_alias: CLIENTELE_REGION_ID
    source_column: clientele_region_id
    target_column: CLIENTELE_REGION_ID
```
and the error is

```Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'CLIENTELE_REGION_ID'
```

I tried all combinations of upper and lowercase, but it always fails with the same error.

**Comment by nehanene15** [comment] 2022-06-01 18:52
Is this a grouped column or an aggregate column?

**Comment by nehanene15** [comment] 2022-06-09 16:16
Duplicate of Issue #504 which has a PR #505 open to resolve this

**Closed as completed by nehanene15** 2022-06-09 16:16 UTC
Labels: type: bug, priority: p1
